name: EKS Infrastructure Pipeline

on:
  push:
    branches:
      - main
      - dev
      - feature/infra-creation

  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - closed

  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Confirm destruction of the selected environment"
        required: true
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_IN_AUTOMATION: true
  TF_INPUT: false

jobs:

  set-environment:
    runs-on: ubuntu-latest

    outputs:
      env_name: ${{ steps.set_env.outputs.env_name }}

    steps:
      - name: Set environment
        id: set_env
        shell: bash
        run: |
          echo "STARTED: Setting environment based on branch..."

          # Detect branch name
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BRANCH="${{ github.base_ref }}"
          else
            BRANCH="${GITHUB_REF#refs/heads/}"
          fi

          echo "Detected branch: $BRANCH"

          # Map branch to environment
          if [[ "$BRANCH" == "main" ]]; then
            echo "Branch '$BRANCH' detected -> setting environment to prod"
            ENV="prod"

          elif [[ "$BRANCH" == "dev" ]]; then
            echo "Branch '$BRANCH' detected -> setting environment to dev"
            ENV="dev"

          elif [[ "$BRANCH" == "feature/infra-creation" ]]; then
            echo "Branch '$BRANCH' detected -> setting environment to dev"
            ENV="dev"

          else
            echo "ERROR: Unsupported branch '$BRANCH'"
            exit 1
          fi

          echo "Branch: $BRANCH"
          echo "Environment: $ENV"

          # Set job output
          echo "env_name=$ENV" >> "$GITHUB_OUTPUT"

          # Verify output
          echo "GitHub output:"
          cat "$GITHUB_OUTPUT"

      - name: Show GitHub repository IDs
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Repository ID: $GITHUB_REPOSITORY_ID"
          echo "Owner: $GITHUB_REPOSITORY_OWNER"
          echo "Owner ID: $GITHUB_REPOSITORY_OWNER_ID"

  terraform-checks:
    name: Terraform checks
    runs-on: ubuntu-latest

    needs: set-environment

    environment:
      name: ${{ needs.set-environment.outputs.env_name }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Show environment
        run: |
          echo "Environment = '${{ needs.set-environment.outputs.env_name }}'"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform version
        run: |
          terraform version

      - name: Terraform Format Check
        run: |
          terraform fmt -check -recursive

      - name: Terraform Init for validation
        run: |
          terraform init \
            -input=false \
            -backend=false

      - name: Terraform Validate
        run: |
          terraform validate


  terraform-int:
    name: Terraform init
    runs-on: ubuntu-latest

    needs:
      - set-environment
      - terraform-checks

    environment:
      name: ${{ needs.set-environment.outputs.env_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -input=false \
            -backend-config="bucket=sdds-terraform-state-dev" \
            -backend-config="key=sdds/${{ needs.set-environment.outputs.env_name }}/terraform.tfstate"


  terraform-plan:
    name: Terraform plan
    runs-on: ubuntu-latest

    needs:
      - set-environment
      - terraform-int

    environment:
      name: ${{ needs.set-environment.outputs.env_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -input=false \
            -backend-config="bucket=sdds-terraform-state-dev" \
            -backend-config="key=sdds/${{ needs.set-environment.outputs.env_name }}/terraform.tfstate"

      - name: Terraform Plan
        run: |
          terraform plan \
            -input=false \
            -var-file="env/dev.tfvars" \
            -out=tfplan

      - name: Upload Terraform plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan
          retention-days: 1


  # terraform-apply:
  #   name: Terraform apply
  #   runs-on: ubuntu-latest
  #   if: >-
  #     github.event_name == 'push' &&
  #     (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main')

  #   needs:
  #     - set-environment
  #     - terraform-plan

  #   environment:
  #     name: ${{ needs.set-environment.outputs.env_name }}

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v5

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v6
  #       with:
  #         role-to-assume: ${{ vars.AWS_ROLE_ARN }}
  #         aws-region: ${{ env.AWS_REGION }}
  #         audience: sts.amazonaws.com

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v3

  #     - name: Terraform Init
  #       run: |
  #         terraform init \
  #           -input=false \
  #           -backend-config="bucket=sdds-terraform-state-dev" \
  #           -backend-config="key=sdds/${{ needs.set-environment.outputs.env_name }}/terraform.tfstate"

  #     - name: Download Terraform plan
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: terraform-plan

  #     - name: Terraform Apply
  #       run: |
  #         terraform apply \
  #           -input=false \
  #           -auto-approve \
  #           tfplan

  #     - name: Terraform Outputs
  #       run: |
  #         terraform output

  #     - name: Verify EKS cluster
  #       run: |
  #         aws eks describe-cluster \
  #           --name dev-sdds-eks \
  #           --region "$AWS_REGION" \
  #           --query 'cluster.status' \
  #           --output text
      #   - name: Configure kubectl
      #   run: |
      #     aws eks update-kubeconfig \
      #       --region "$AWS_REGION" \
      #       --name dev-sdds-eks

      # - name: Verify Kubernetes nodes
      #   run: |
      #     kubectl get nodes -o wide

      # - name: Verify Kubernetes system pods
      #   run: |
      #     kubectl get pods -A

      # - name: EKS deployment summary
      #   run: |
      #     echo "=========================================="
      #     echo " EKS INFRASTRUCTURE CREATED SUCCESSFULLY"
      #     echo "=========================================="
      #     echo "Cluster: dev-sdds-eks"
      #     echo "Region: $AWS_REGION"
      #     echo "Nodes:"
      #     kubectl get nodes
      #     echo "Cluster Status:"
      #     aws eks describe-cluster \
      #       --name dev-sdds-eks \
      #       --region "$AWS_REGION" \
      #       --query 'cluster.status' \
      #       --output text

  terraform-destroy:
    name: Terraform Destroy
    if: >
      always() &&
      needs.terraform-plan.result == 'success' &&
      (
        (
          github.event_name == 'pull_request' &&
          github.event.action == 'closed' &&
          github.event.pull_request.merged == true &&
          (github.base_ref == 'dev' || github.base_ref == 'main')
        ) ||
        (
          github.event_name == 'push' &&
          (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main') &&
          startsWith(github.event.head_commit.message, 'Merge pull request')
        )
      )
    needs:
      - set-environment
      - set-environment
      - terraform-plan
    runs-on: ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -input=false \
            -backend-config="bucket=sdds-terraform-state-dev" \
            -backend-config="key=sdds/${{ needs.set-environment.outputs.env_name }}/terraform.tfstate"
            -backend-config="key=sdds/${{ needs.set-environment.outputs.env_name }}/terraform.tfstate"

      - name: Terraform Destroy
        run: |
          terraform destroy \
            -input=false \
            -auto-approve \
            -var-file="env/dev.tfvars"